sudo: false
dist: trusty

language: node_js
node_js:
  - "8"

cache: yarn

addons:
  chrome: stable

before_install:
  - "curl -o- -L https://yarnpkg.com/install.sh | bash -s --"
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --non-interactive

script:
  - yarn test
